# Generated by Django 4.1.7 on 2023-03-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manager_name', models.CharField(max_length=50)),
                ('Manager_phone', models.CharField(max_length=50)),
                ('Manager_email', models.CharField(max_length=50)),
                ('Manager_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Manager_tb',
            },
        ),
    ]
