# Generated by Django 4.1.7 on 2023-03-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Manager',
        ),
    ]
