# Generated by Django 4.1.7 on 2023-03-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0002_rename_customer_manager'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manager',
            table='manager_tb',
        ),
    ]
