# Generated by Django 4.1.7 on 2023-03-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='remark',
            field=models.CharField(default='', max_length=500),
        ),
    ]
