# Generated by Django 4.1.7 on 2023-03-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cce', '0002_complaint_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='customer_email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
