# Generated by Django 4.1.7 on 2023-03-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cce', '0003_alter_complaint_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='purchase_date',
            field=models.DateField(default=''),
        ),
    ]
