# Generated by Django 4.1.7 on 2023-03-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cce', '0004_alter_complaint_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_date',
            field=models.DateField(default=''),
        ),
    ]
