# Generated by Django 4.1.7 on 2023-04-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cce', '0005_alter_complaint_complaint_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='serial',
            field=models.CharField(default='', max_length=50),
        ),
    ]
