# Generated by Django 4.1.7 on 2023-03-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tec_name', models.CharField(max_length=50)),
                ('tec_phone', models.CharField(max_length=50)),
                ('tec_email', models.CharField(max_length=50)),
                ('tec_age', models.IntegerField()),
                ('tec_gender', models.CharField(max_length=50)),
                ('tec_Address', models.CharField(max_length=500)),
                ('tec_location', models.CharField(max_length=50)),
                ('tec_photo', models.ImageField(upload_to='technician/')),
                ('tec_jdate', models.DateField()),
                ('tec_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'technician_tb',
            },
        ),
    ]
