# Generated by Django 4.1.7 on 2023-03-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0005_product_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Manager.location'),
        ),
    ]
