# Generated by Django 4.1.7 on 2023-03-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0007_alter_technician_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='location',
        ),
    ]
